### ISSUE TITLE
Unify handling of dependencies

### ISSUE THREAD

**Issue by JJ** [mmore500/hstrat#54]
### Description

This project has both pyproject.toml as well as requirements*.txt files. Best practices (and PEPs) have settled on the former. It should make sure it follows current best practices, and at any rate only one of them.

**Comment by mmore500** [comment]
Agreed that this should be streamlined. Will make ongoing maintenance a lot easier (as well as being less confusing for people looking through/contributing). Worked on this in #57. I got rid of `setup.py` but did keep the `requirements.txt` in `requirements-dev/`. These are generated with pip-tools and thoroughly pin the entire install, so are useful to keep package changes from randomly breaking the CI.

I will add a note in the documentation about how to install development dependencies.

**Comment by JJ** [comment]
You should probably keep requirements.txt only for `poetry` and `tox`. Just for simplicity. The rest should be handled by pyproject.toml

**Comment by mmore500** [comment]
Yep, `pyproject.toml` is doing all the heavy lifting. Under the hood, it's being to generate the full-pinned `requirements.txt` files using pip-tools compile. I have updated `CONTRIBUTING.rst` with current instructions for developer setup.

**Comment by mmore500** [comment]
Going to close this for now. Happy to discuss further ideas for improvements, though.
