### ISSUE TITLE
Link pointing to the wrong repository?

### ISSUE THREAD

**Issue by osorensen** [mmore500/hstrat#77]
This is an editorial comment on the [JOSS submission](https://github.com/openjournals/joss-reviews/issues/4866)

The link https://doi.org/10.5281/zenodo.4141943 for the reference Ofria et al. (2020) leads me to the following webpage. Is that correct?

![image](https://user-images.githubusercontent.com/21175639/206179789-dbd2b031-1b92-4548-afa3-502207828f10.png)

**Comment by mmore500** [comment]
Yes. That is the intended software citation.
